server {
    listen 80;
    # Rediriger HTTP vers HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 162.38.111.43;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    root /usr/share/nginx/html;
    index index.html;

    # Frontend (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend (API)
    location /api/ {
        proxy_pass http://backend:4000/api/;
        proxy_set_header Host $host;
    }
}
